syntax on

set noerrorbells
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set number relativenumber
set smartcase
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set incsearch
set nohlsearch
set colorcolumn=80
highlight ColorColumn ctermbg=0 guibg=lightgrey

call plug#begin('~/.vim/plugged')
Plug 'morhetz/gruvbox'
Plug 'vimwiki/vimwiki'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'junegunn/fzf.vim'
Plug 'cespare/vim-toml'
call plug#end()

let mapleader = ' '
nnoremap Y y$

if &term =~ '256color'
    " Disable Background Color Erase (BCE) so that color schemes
    " work properly when Vim is used inside tmux and GNU screen.
    set t_ut=
endif

" gruvbox
let g:gruvbox_contrast_dark = 'hard'
colorscheme gruvbox
set background=dark

" vimwiki
let g:vimwiki_list = [{'path': '~/Documents/wiki', 'syntax': 'markdown', 'ext': '.md'}]

" coc
call coc#add_extension('coc-json', 'coc-rls', 'coc-snippets', 'coc-markdownlint', 'coc-python')
runtime config/coc.vim

" fzf
nnoremap <leader><leader> :GFiles<CR>
nnoremap <leader>ff       :Files<CR>
nnoremap <leader>fd       :Buffers<CR>
nnoremap <leader>fl       :Lines<CR>
nnoremap <leader>fw       :Windows<CR>
nnoremap <leader>fs       :Rg<CR>
nnoremap <leader>fc       :Commits<CR>
nnoremap <leader>fb       :BCommits<CR>
nnoremap <leader>fh       :History<CR>
nnoremap <leader>fm       :Maps<CR>

