syntax on

set noerrorbells
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set number relativenumber
set smartcase
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set incsearch

set colorcolumn=80
highlight ColorColumn ctermbg=0 guibg=lightgrey

call plug#begin('~/.vim/plugged')
Plug 'morhetz/gruvbox'
Plug 'vimwiki/vimwiki'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'junegunn/fzf.vim'
call plug#end()

let g:vimwiki_list = [{'path': '~/Documents/wiki', 'syntax': 'markdown', 'ext': '.md'}]

let mapleader = ' '

if &term =~ '256color'
    " Disable Background Color Erase (BCE) so that color schemes
    " work properly when Vim is used inside tmux and GNU screen.
    set t_ut=
endif

let g:gruvbox_contrast_dark = 'hard'
colorscheme gruvbox
set background=dark

runtime config/coc.vim

" fzf
nnoremap <leader><leader> :Files<CR>
nnoremap <leader>fg       :GFiles<CR>
nnoremap <leader>ff       :Buffers<CR>
nnoremap <leader>fl       :Lines<CR>
nnoremap <leader>fw       :Windows<CR>
nnoremap <leader>fs       :Rg<CR>
nnoremap <leader>fc       :Commits<CR>
nnoremap <leader>fb       :BCommits<CR>
nnoremap <leader>fh       :History<CR>
nnoremap <leader>fm       :Maps<CR>

